### ISSUE TITLE
how to write loops ?

### ISSUE THREAD

**Issue by Gozala** [jaredly/jerd#8]
I was unable to figure out how to write loops other then with recursive function. @jaredly I think you've mentioned something about special syntax to denote recursion that would cause compiler to do a tail call elimination, but I was unable to find any example code illustrating it nor I a was able to find it by scanning through the source code.

Creating issue which we can close once we have example code illustrating it.

**Comment by jaredly** [comment]
I'm planning on adding a `loop/recur` construct, haven't gotten around to it just yet. It will look something like:
```
// add x and y very slowly
loop{x: initialX, y: initialY} {
  // blah blah
  if x > 0 {
    recur({x: x - 1, y: y + 1})
  } else {
    y
  }
}
```

**Comment by jaredly** [comment]
Ok, I've ditched the loop/recur idea for the moment, instead opting to detect opportunities to convert tail-call self-recursion into a while loop.
So this is now optimized, for example:
```
const fib: (int, int, int) => int = (prev: int, cur: int, n: int):int => if n == 0 {
    prev
} else {
    fib(cur, prev + cur, n - 1)
}
```
